"""add ai fields to complaints

Revision ID: 20fbda14ae3a
Revises: 44e712b14245
Create Date: 2026-07-31 23:32:16.977015

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20fbda14ae3a'
down_revision: Union[str, Sequence[str], None] = '44e712b14245'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('complaints', sa.Column('ai_category', sa.String(length=100), nullable=True))
    op.add_column('complaints', sa.Column('ai_priority', sa.String(length=50), nullable=True))
    op.add_column('complaints', sa.Column('sentiment', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('complaints', 'sentiment')
    op.drop_column('complaints', 'ai_priority')
    op.drop_column('complaints', 'ai_category')
    # ### end Alembic commands ###
