"""add urgency score

Revision ID: 744bb50a9157
Revises: 05f578b3a259
Create Date: 2026-08-01 00:08:23.557436

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '744bb50a9157'
down_revision: Union[str, Sequence[str], None] = '05f578b3a259'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('complaints', sa.Column('urgency_score', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('complaints', 'urgency_score')
    # ### end Alembic commands ###
