"""add complaint location

Revision ID: 9a60cd3e2aca
Revises: fcf817fb08a4
Create Date: 2026-08-01 11:56:26.120393

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a60cd3e2aca'
down_revision: Union[str, Sequence[str], None] = 'fcf817fb08a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('complaints', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('complaints', sa.Column('longitude', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('complaints', 'longitude')
    op.drop_column('complaints', 'latitude')
    # ### end Alembic commands ###
