"""add cluster id

Revision ID: fcf817fb08a4
Revises: 744bb50a9157
Create Date: 2026-08-01 11:11:00.924697

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fcf817fb08a4'
down_revision: Union[str, Sequence[str], None] = '744bb50a9157'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('complaints', sa.Column('cluster_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('complaints', 'cluster_id')
    # ### end Alembic commands ###
